<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <style>
        body {
            background-color: black;
            color: white;
        }
        .image-container .image-caption {
            position: absolute;
            top: 27%;
            left: 0;
            width: 100%;
            text-align: center;
            color: white;
            font-size: 40px;
        }
        .f {
            margin-left: 100px;
            margin-right: 100px;
        }
        .text-white {
            color: white;
        }
        .text-stretched {
            width: 100%;
        }
    </style>
</head>
<body>
<div class="container">
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
            <img src="img_1.png" width="150" height="40" alt="Картинка">
        </a>

        <ul class="nav nav-pills">
            <li class="nav-item"><a href="/home" class="nav-link" aria-current="page">Главная</a></li>
            <li class="nav-item"><a href="con" class="nav-link">Контакты</a></li>
            <li class="nav-item"><a href="ab" class="nav-link active">О нас</a></li>
            <li class="nav-item"><a href="reg" class="nav-link">Аккаунт</a></li>
        </ul>
    </header>
</div>

<div class="image-container">
    <img src="img.png" style="width: 100%; height: 202px;" alt="Картинка">
    <div class="image-caption">О нас</div>
</div>
<h1 class="display-4 fst-italic text-stretched">                     История нашей компании</h1>
<p class="lead my-3 text-stretched text-white">        Пять лет назад новое ивент-агентство было создано с целью организации неповторимых мероприятий. Они собрали команду профессионалов и стали известными благодаря креативным и оригинальным концепциям. За это время агентство завоевало репутацию надежного и инновационного партнера. Они организовывают разнообразные корпоративные мероприятия и презентации.</p>
</body>
</html>